/**
 * Test Practice Set generation directly calling backend API endpoint
 * Run with: npx tsx backend/test-practice-direct.ts [sessionId]
 */

import { readFileSync } from 'fs'
import { resolve } from 'path'

// Load environment variables
try {
  const envFile = readFileSync(resolve(__dirname, '.env.local'), 'utf-8')
  envFile.split('\n').forEach(line => {
    const match = line.match(/^([^#=]+)=(.*)$/)
    if (match) {
      const key = match[1].trim()
      const value = match[2].trim()
      if (!process.env[key]) {
        process.env[key] = value
      }
    }
  })
} catch (error) {
  console.warn('Could not load .env.local')
}

import { createClient } from '@supabase/supabase-js'
import { generatePracticeSetDescription, createPracticeSet } from './lib/opennote'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing Supabase credentials')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey)

async function testPracticeGeneration(sessionId: string) {
  console.log('='.repeat(80))
  console.log(`TESTING PRACTICE SET GENERATION (DIRECT): ${sessionId}`)
  console.log('='.repeat(80))
  console.log()

  // Fetch session data directly from database
  console.log('1. Fetching session data from database...')
  const { data: session, error: sessionError } = await supabase
    .from('sessions')
    .select('*')
    .eq('id', sessionId)
    .single()

  if (sessionError || !session) {
    console.error('❌ Session not found:', sessionError?.message)
    return
  }

  console.log(`   ✅ Session found: ${session.status}`)
  console.log(`   Started: ${new Date(session.started_at).toLocaleString()}`)
  console.log(`   Intent: ${session.intent_text || 'None'}`)
  console.log()

  // Fetch events
  console.log('2. Fetching events...')
  const { data: events, error: eventsError } = await supabase
    .from('events')
    .select('*')
    .eq('session_id', sessionId)
    .order('ts', { ascending: true })

  if (eventsError) {
    console.error('❌ Error fetching events:', eventsError.message)
    return
  }

  console.log(`   ✅ Found ${events?.length || 0} events`)
  if (events && events.length > 0) {
    console.log(`   First event: ${events[0].url}`)
    console.log(`   Last event: ${events[events.length - 1].url}`)
  }
  console.log()

  // Fetch analysis
  console.log('3. Fetching analysis...')
  const { data: analysis } = await supabase
    .from('analysis')
    .select('summary_json')
    .eq('session_id', sessionId)
    .single()

  if (analysis) {
    console.log('   ✅ Analysis found')
  } else {
    console.log('   ⚠️  Analysis not found (will use fallback)')
  }
  console.log()

  // Prepare session data
  const sessionData = {
    session: {
      id: session.id,
      status: session.status,
      started_at: session.started_at,
      ended_at: session.ended_at,
      intent_text: session.intent_text,
      created_at: session.created_at
    },
    events: events || [],
    analysis: analysis?.summary_json || null
  }

  // Generate practice description
  console.log('4. Generating practice set description...')
  const practiceDesc = generatePracticeSetDescription(sessionData)
  console.log(`   ✅ Practice description generated (${practiceDesc.length} characters)`)
  console.log()
  console.log('Description:')
  console.log('-'.repeat(80))
  console.log(practiceDesc)
  console.log('-'.repeat(80))
  console.log()

  // Build webhook URL
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'
  const webhookUrl = `${appUrl}/api/opennote/practice/webhook`
  
  console.log('5. Creating practice set via Opennote API...')
  console.log(`   Webhook URL: ${webhookUrl}`)
  console.log()

  try {
    const practiceResult = await createPracticeSet(practiceDesc, 5, webhookUrl)
    console.log('   ✅ Practice set creation successful!')
    console.log()
    console.log('='.repeat(80))
    console.log('SUCCESS!')
    console.log('='.repeat(80))
    console.log(`Set ID: ${practiceResult.setId}`)
    console.log()
    console.log('📝 Practice set is being generated by Opennote.')
    console.log('   It will be delivered via webhook when ready.')
    console.log('   Webhook URL:', webhookUrl)
    console.log()
    console.log('⚠️  Note: If you see a 404 from Opennote, the practice API endpoint')
    console.log('   may not be available yet. Journal export is the main feature.')
    console.log('='.repeat(80))
  } catch (error: any) {
    console.error('   ❌ Practice set creation failed:', error.message)
    console.log()
    console.log('This is expected if:')
    console.log('1. Opennote Practice API endpoint doesn\'t exist (404) - this is OK, it\'s a bonus feature')
    console.log('2. Invalid API key - check OPENNOTE_API_KEY in .env.local')
    console.log('3. Network issues - check internet connection')
    console.log()
    console.log('The practice API endpoint is optional - journal export is the main feature.')
    console.log('Full error:', error.message)
  }
}

async function main() {
  const sessionId = process.argv[2] || '8c52f524-3dd2-4051-9a9f-6eaf7460be28'
  await testPracticeGeneration(sessionId)
}

main().catch(console.error)
