/**
 * Test Practice Set generation with FIXED endpoint and real API
 * Run with: npx tsx backend/test-practice-fixed.ts
 */

import { readFileSync } from 'fs'
import { resolve } from 'path'

// Load environment variables
try {
  const envFile = readFileSync(resolve(__dirname, '.env.local'), 'utf-8')
  envFile.split('\n').forEach(line => {
    const match = line.match(/^([^#=]+)=(.*)$/)
    if (match) {
      const key = match[1].trim()
      const value = match[2].trim()
      if (!process.env[key]) {
        process.env[key] = value
      }
    }
  })
} catch (error) {
  console.warn('Could not load .env.local')
}

import { generatePracticeSetDescription, createPracticeSet } from './lib/opennote'

// Mock session data based on real session structure
// This simulates what would come from a real session with events
const mockSessionDataReal = {
  session: {
    id: '8c52f524-3dd2-4051-9a9f-6eaf7460be28',
    status: 'running',
    started_at: '2026-01-17T21:59:00Z',
    ended_at: null,
    intent_text: null,
    created_at: '2026-01-17T21:59:00Z'
  },
  events: [
    {
      id: 'event-1',
      url: 'https://leetcode.com/problems/two-sum',
      title: 'Two Sum - LeetCode',
      duration_sec: 600,
      domain: 'leetcode.com',
      ts: 1705519140000
    },
    {
      id: 'event-2',
      url: 'https://leetcode.com/problems/valid-parentheses',
      title: 'Valid Parentheses',
      duration_sec: 900,
      domain: 'leetcode.com',
      ts: 1705519740000
    },
    {
      id: 'event-3',
      url: 'https://docs.google.com/document/d/test123',
      title: 'System Design Notes',
      duration_sec: 1200,
      domain: 'docs.google.com',
      ts: 1705520640000
    }
  ],
  analysis: {
    goalInferred: 'Interview preparation - algorithms and system design',
    workspaces: [
      {
        label: 'LeetCode Practice',
        timeSec: 1500,
        topUrls: [
          'https://leetcode.com/problems/two-sum',
          'https://leetcode.com/problems/valid-parentheses'
        ]
      },
      {
        label: 'Documentation Review',
        timeSec: 1200,
        topUrls: [
          'https://docs.google.com/document/d/test123'
        ]
      }
    ],
    resumeSummary: 'You were practicing LeetCode problems and reviewing system design documentation',
    lastStop: {
      label: 'System Design Notes',
      url: 'https://docs.google.com/document/d/test123'
    },
    nextActions: ['Continue with more LeetCode problems', 'Review stack data structure'],
    pendingDecisions: []
  }
}

async function testPracticeGeneration() {
  console.log('='.repeat(80))
  console.log('TESTING PRACTICE SET GENERATION WITH FIXED ENDPOINT')
  console.log('='.repeat(80))
  console.log()

  const apiKey = process.env.OPENNOTE_API_KEY
  if (!apiKey) {
    console.error('❌ OPENNOTE_API_KEY not found in environment')
    process.exit(1)
  }

  console.log('✅ API Key found:', apiKey.substring(0, 20) + '...')
  console.log()

  try {
    // Generate practice description
    console.log('1. Generating practice set description from session data...')
    const practiceDesc = generatePracticeSetDescription(mockSessionDataReal)
    console.log(`   ✅ Practice description generated (${practiceDesc.length} characters)`)
    console.log()
    console.log('Description:')
    console.log('-'.repeat(80))
    console.log(practiceDesc)
    console.log('-'.repeat(80))
    console.log()

    // Test with Opennote API (FIXED endpoint)
    console.log('2. Creating practice set via Opennote API (FIXED endpoint)...')
    console.log('   Endpoint: /v1/interactives/practice/create')
    console.log('   Parameters:')
    console.log(`     - num_problems: 5`)
    console.log(`     - set_description: (shown above)`)
    console.log()

    const webhookUrl = process.env.NEXT_PUBLIC_APP_URL 
      ? `${process.env.NEXT_PUBLIC_APP_URL}/api/opennote/practice/webhook`
      : 'https://yourapp.vercel.app/api/opennote/practice/webhook'

    const practiceResult = await createPracticeSet(
      practiceDesc,
      5,
      webhookUrl,
      `FocusForge Session ${mockSessionDataReal.session.id.slice(0, 8)}`
    )

    console.log('   ✅ Practice set creation successful!')
    console.log()
    console.log('='.repeat(80))
    console.log('SUCCESS!')
    console.log('='.repeat(80))
    console.log(`Set ID: ${practiceResult.setId}`)
    if (practiceResult.status) {
      console.log(`Status: ${practiceResult.status}`)
    }
    console.log()
    console.log('📝 Practice set is being generated by Opennote.')
    console.log('   The problems will be delivered via webhook when ready.')
    console.log(`   Webhook URL: ${webhookUrl}`)
    console.log()
    console.log('🎉 Practice generation with real data structure works!')
    console.log('='.repeat(80))

  } catch (error: any) {
    console.error('❌ Practice set creation failed:', error.message)
    console.log()
    console.log('Error details:', error)
    console.log()
    console.log('This might be due to:')
    console.log('1. Invalid API key (make sure it\'s editable)')
    console.log('2. Rate limit exceeded (3 requests/minute on Developer tier)')
    console.log('3. Network issues')
    console.log('4. Opennote API changes')
  }
}

testPracticeGeneration().catch(console.error)
